MAXIMUM_FIELDS_NUMBER = 5
WORKERS = "employees"
WORKER = 'worker'

LOCATION = "location"
DESTINATION = 'destination'
FIELDS = "fields"
FARM = 'FARM'

STOCK = "stock"
NEEDED_WATER = "needed_water"
FACTORY_SOUPE = ("soup_factory", "CUISINER",'SOUP_FACTORY')
FACTORY_STOCK = ("USINE",'SOUP_FACTORY')
CONTENT = "content"
TRACTORS = 'tractors'

POTATO = ('POTATO', 'PATATE')
LEEK = ('LEEK', 'POIREAU')
TOMATO = ('TOMATO', 'TOMATE')
ONION = ('ONION', 'OIGNON')
ZUCCHINI = ('ZUCCHINI', 'COURGETTE')

VEGETABLES = {
    'POTATO': 'PATATE',
    'LEEK': 'POIREAU',
    'TOMATO': 'TOMATE',
    'ONION': 'OIGNON',
    'ZUCCHINI': 'COURGETTE'
}
