name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        name: vpoulailleau/chronobio
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        ls
        cd aigrisculteurs
        git clone git@github.com:vpoulailleau/chronobio.git
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
